// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpxhgrkiqvmgdmwgvaye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweGhncmtpcXZtZ2Rtd2d2YXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDUyMjUsImV4cCI6MjA1OTMyMTIyNX0.PDADrsvKskn6AV04jamVWAQsEVcJVw2EBe8ODBAVyTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);